### ISSUE TITLE
UI画布的缩放设置

### ISSUE THREAD

**Issue by ScintillaH** [Kannmu/UnityExperimentTemplate#6]
目前UI仅在1080P分辨率下可正常呈现，其他的屏幕宽度均会导致黑边或者裁剪问题。
建议对画布的Canvas Scaler组件做如下修改：
1. 将缩放模式设置为Scale With Screen Size模式；
2. 设置Reference Solution的Y值为1080；
3. 将匹配模式设置为Match Width Or Height；
4. 将Match设置为1（完全匹配高度）。

**Comment by Kannmu** [comment]
十分感谢！这就修改
